// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (https://www.specflow.org/).
//      SpecFlow Version:3.9.0.0
//      SpecFlow Generator Version:3.9.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
// Generation customised by SpecFlow.Contrib.Variants v3.9.90-pre.1
namespace Tests.Features
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("Attempting login with no username shows error")]
    [NUnit.Framework.CategoryAttribute("Variant:Chrome")]
    [NUnit.Framework.CategoryAttribute("Variant:Edge")]
    public partial class AttemptingLoginWithNoUsernameShowsErrorFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "Login_UsernameRequired.feature"
#line hidden
        
        [NUnit.Framework.OneTimeSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Features", "Attempting login with no username shows error", null, ProgrammingLanguage.CSharp, new string[] {
                        "Variant:Chrome",
                        "Variant:Edge"});
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.OneTimeTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<NUnit.Framework.TestContext>(NUnit.Framework.TestContext.CurrentContext);
        }
        
        public virtual void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        public virtual void FeatureBackground()
        {
            testRunner.Given("the user is on the login page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
        }
        
        [NUnit.Framework.TestCaseAttribute("standard_user", "secret_sauce", "Chrome", null, Category="Variant:Chrome", TestName="ClearingAllCredentialsShowsUsernameRequiredError with Chrome and \"standard_user\"," +
            " \"secret_sauce\"")]
        [NUnit.Framework.TestCaseAttribute("standard_user", "secret_sauce", "Edge", null, Category="Variant:Edge", TestName="ClearingAllCredentialsShowsUsernameRequiredError with Edge and \"standard_user\", \"" +
            "secret_sauce\"")]
        [NUnit.Framework.TestCaseAttribute("locked_out_user", "secret_sauce", "Chrome", null, Category="Variant:Chrome", TestName="ClearingAllCredentialsShowsUsernameRequiredError with Chrome and \"locked_out_user" +
            "\", \"secret_sauce\"")]
        [NUnit.Framework.TestCaseAttribute("locked_out_user", "secret_sauce", "Edge", null, Category="Variant:Edge", TestName="ClearingAllCredentialsShowsUsernameRequiredError with Edge and \"locked_out_user\"," +
            " \"secret_sauce\"")]
        [NUnit.Framework.TestCaseAttribute("problem_user", "secret_sauce", "Chrome", null, Category="Variant:Chrome", TestName="ClearingAllCredentialsShowsUsernameRequiredError with Chrome and \"problem_user\", " +
            "\"secret_sauce\"")]
        [NUnit.Framework.TestCaseAttribute("problem_user", "secret_sauce", "Edge", null, Category="Variant:Edge", TestName="ClearingAllCredentialsShowsUsernameRequiredError with Edge and \"problem_user\", \"s" +
            "ecret_sauce\"")]
        [NUnit.Framework.TestCaseAttribute("performance_glitch_user", "secret_sauce", "Chrome", null, Category="Variant:Chrome", TestName="ClearingAllCredentialsShowsUsernameRequiredError with Chrome and \"performance_gli" +
            "tch_user\", \"secret_sauce\"")]
        [NUnit.Framework.TestCaseAttribute("performance_glitch_user", "secret_sauce", "Edge", null, Category="Variant:Edge", TestName="ClearingAllCredentialsShowsUsernameRequiredError with Edge and \"performance_glitc" +
            "h_user\", \"secret_sauce\"")]
        [NUnit.Framework.TestCaseAttribute("error_user", "secret_sauce", "Chrome", null, Category="Variant:Chrome", TestName="ClearingAllCredentialsShowsUsernameRequiredError with Chrome and \"error_user\", \"s" +
            "ecret_sauce\"")]
        [NUnit.Framework.TestCaseAttribute("error_user", "secret_sauce", "Edge", null, Category="Variant:Edge", TestName="ClearingAllCredentialsShowsUsernameRequiredError with Edge and \"error_user\", \"sec" +
            "ret_sauce\"")]
        [NUnit.Framework.TestCaseAttribute("visual_user", "secret_sauce", "Chrome", null, Category="Variant:Chrome", TestName="ClearingAllCredentialsShowsUsernameRequiredError with Chrome and \"visual_user\", \"" +
            "secret_sauce\"")]
        [NUnit.Framework.TestCaseAttribute("visual_user", "secret_sauce", "Edge", null, Category="Variant:Edge", TestName="ClearingAllCredentialsShowsUsernameRequiredError with Edge and \"visual_user\", \"se" +
            "cret_sauce\"")]
        [NUnit.Framework.TestCaseAttribute("invalid_user", "secret_sauce", "Chrome", null, Category="Variant:Chrome", TestName="ClearingAllCredentialsShowsUsernameRequiredError with Chrome and \"invalid_user\", " +
            "\"secret_sauce\"")]
        [NUnit.Framework.TestCaseAttribute("invalid_user", "secret_sauce", "Edge", null, Category="Variant:Edge", TestName="ClearingAllCredentialsShowsUsernameRequiredError with Edge and \"invalid_user\", \"s" +
            "ecret_sauce\"")]
        [NUnit.Framework.TestCaseAttribute("standard_user", "sauce_secret", "Chrome", null, Category="Variant:Chrome", TestName="ClearingAllCredentialsShowsUsernameRequiredError with Chrome and \"standard_user\"," +
            " \"sauce_secret\"")]
        [NUnit.Framework.TestCaseAttribute("standard_user", "sauce_secret", "Edge", null, Category="Variant:Edge", TestName="ClearingAllCredentialsShowsUsernameRequiredError with Edge and \"standard_user\", \"" +
            "sauce_secret\"")]
        public virtual void ClearingAllCredentialsShowsUsernameRequiredError(string username, string password, string variant, string[] exampleTags)
        {
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("username", username);
            argumentsOfScenario.Add("password", password);
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo(string.Format("{0}: {1}", "Clearing all credentials shows username required error", variant), null, exampleTags, argumentsOfScenario);
            this.ScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.Add("Variant", variant);
            this.ScenarioStart();
            this.FeatureBackground();
            testRunner.Given(string.Format("the user enters username \"{0}\" and password \"{1}\"", username, password), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
            testRunner.When("the user clears the username", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
            testRunner.And("the user clears the password", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
            testRunner.And("the user clicks the login button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
            testRunner.Then("the user should see the error \"Username is required\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
